version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "5173:80"
    depends_on:
      - api-gateway

  api-gateway:
    build: ../api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=super_secret_key_change_me
      - AUTH_SERVICE_URL=http://auth-service:8000
      - CHAT_SERVICE_URL=http://chat-service:3001
      - ROUTES_SERVICE_URL=http://routes-service:4000
      - FRONTEND_URL=http://localhost:5173
      - COOKIE_MAX_AGE=1800
    depends_on:
      - auth-service
      - routes-service
      - chat-service

  chat-service:
    build: ../chat-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/uniwheels_chat
      - JWT_ACCESS_SECRET=super_secret_key_change_me
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo

  routes-service:
    build: ../routes-reservations-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/routesdb
      - JWT_SECRET=super_secret_key_change_me
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/var/lib/mongodb/data

  auth-service:
    build: ../loggueo_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/loggeo_base_db
      - SECRET_KEY=super_secret_key_change_me
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=loggeo_base_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d loggeo_base_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
