worker_processes auto;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    upstream loggueo_pool {
        ip_hash;
        server loggueo_1:8000 max_fails=3 fail_timeout=30s;
        server loggueo_2:8000 max_fails=3 fail_timeout=30s;
        server loggueo_3:8000 max_fails=3 fail_timeout=30s;
        keepalive 128;
    }

    server {
        listen 8000;
        server_name localhost;

        location = /healthz {
            access_log off;
            default_type application/json;
            return 200 '{"status":"ok","service":"loggueo-lb"}';
        }

        location / {
            proxy_pass         http://loggueo_pool;
            proxy_http_version 1.1;
            proxy_set_header   Connection        "";
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_connect_timeout 10s;
            proxy_send_timeout    60s;
            proxy_read_timeout    60s;
        }
    }
}
